import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';

import { TopNav } from '@/components/TopNav';

import './globals.css';

import { AuthProvider } from '@/contexts';

const kanit = Kanit({
    weight: ['400'],
    variable: '--font-kanit',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Class Room EP105',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${kanit.variable} antialiased`}>
                <AuthProvider>
                    <TopNav />
                    <main className="p-4">{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
